### ISSUE TITLE
Add deploy rpm / deb packages

### ISSUE THREAD

**Issue by ArtDu** [tarantool/expirationd#56] opened 2021-06-01 12:47 UTC
Build and deploy rpm / deb packages to systems on gh actions, as was done in travis.yml https://github.com/tarantool/expirationd/blob/1.0.1/.travis.yml

**Comment by Totktonada** [comment] 2021-06-09 20:00
Duplicate of #43.

My bad: I didn't checked, whether it is already exists, and suggested Artem to file an issue regarding deploying of RPM / Deb packages.

**Closed by Totktonada** 2021-06-09 20:00 UTC
Labels: ci
