### ISSUE TITLE
Need explain `full_scan_time` more detailed 

### ISSUE THREAD

**Issue by skeris** [tarantool/expirationd#66] opened 2021-07-23 17:42 UTC
Now in readme no such explanations of  what is full_scan_time, iteration_delay, full_scan_delay.
1. "full_scan_time - Time required for a full index scan (in seconds)." - is it the max time spend for full scan ? or this time must be spent to scan? 
2. "iteration_delay - Max sleep time between batches (in seconds)." - why max? Can batch awake ahead of time?
3. "full_scan_delay - Sleep time between full scans (in seconds)." - full scans maddening me. how does it works?

**Comment by skeris** [comment] 2021-07-23 17:44
Please, add more examples with comments to readme.

**Comment by Totktonada** [comment] 2021-07-23 22:01
It seems, it is duplicate of #38. You can find there a comment, which explains how expirationd works.

**Closed** 2021-08-05 09:27 UTC
Labels: documentation, duplicate
