### ISSUE TITLE
Potential Bug: CPU Usage Increase

### ISSUE THREAD

**Issue by ASverdlov** [tarantool/expirationd#33] opened 2018-06-22 15:45 UTC
# Problem
Allegedly, there is a bug, which causes CPU usage increase.
Apparently, no sleeping occurs inside infinite loop in a worker fiber.

# Possible Reproduction Scenario
There is less tuples in space than it's configured to process.

# Some Comments
I will attach minimal test case for reproducing the behaviour later.
For now, this is just a suspicion.
Feel free to close the issue if no activity happens for a long time or contact me and school on my laziness and lack of responsibility.

**Comment by Totktonada** [comment] 2020-10-24 02:45
I looked over the code and I don't see any obvious problems in it.

I created a simple test:

```lua
#!/usr/bin/env tarantool

local expirationd = require('expirationd')
local log = require('log')

box.cfg()

box.once('init', function()
    box.schema.create_space('s')
    box.space.s:create_index('pk')
end)

box.space.s:truncate()

for i = 1, 10 do
    box.space.s:insert({i})
end

local function is_tuple_expired(_, tuple)
    log.info(('is_tuple_expired(_, {%d})'):format(tuple[1]))
    return true
end

local function process_expired_tuple(_, _, tuple)
    log.info(('process_expired_tuple(_, _, {%d})'):format(tuple[1]))
    -- Do nothing.
end

expirationd.start('expire s', 's', is_tuple_expired, {
    process_expired_tuple = process_expired_tuple,
    tuples_per_iteration = 1024,
    full_scan_time = 60,
})
```

I played around different values: a space length below and above the `tuples_per_iteration` value. The behaviour is expected: the delay between processing of `min(space_len, tuples_per_iteration)` tuples is calculated as `tuples_per_iteration` × `full_scan_time` / `space_length` (but not beyond 1 second).

Since I know the project Albert said about, I know where to ask an actual information. @amitichev, do you observe any problems around CPU usage and expirationd? Can you provide more information here?

**Comment by Totktonada** [comment] 2020-11-19 07:36
I asked @amitichev, whether he observed behaviour of this kind, and the answer is 'no'. Since we unable to reproduce it and don't see such behaviour anywhere, I'll close the issue.

**Closed by Totktonada** 2020-11-19 07:36 UTC
Labels: bug, need feedback
